#!/bin/bash
# OffCall AI Agent Installer
# Usage: curl -fsSL $OFFCALL_URL/install.sh | OFFCALL_API_KEY=xxx bash

set -e

# Configuration
AGENT_VERSION="${OFFCALL_AGENT_VERSION:-latest}"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/offcall-agent"
DATA_DIR="/var/lib/offcall-agent"
GITHUB_REPO="offcallai/agent"
BINARY_NAME="offcall-agent"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
check_root() {
    if [ "$EUID" -ne 0 ]; then
        log_error "Please run as root or with sudo"
        exit 1
    fi
}

# Detect OS and architecture
detect_platform() {
    OS=$(uname -s | tr '[:upper:]' '[:lower:]')
    ARCH=$(uname -m)

    case $ARCH in
        x86_64)
            ARCH="amd64"
            ;;
        aarch64|arm64)
            ARCH="arm64"
            ;;
        *)
            log_error "Unsupported architecture: $ARCH"
            exit 1
            ;;
    esac

    case $OS in
        linux)
            ;;
        darwin)
            ;;
        *)
            log_error "Unsupported operating system: $OS"
            exit 1
            ;;
    esac

    PLATFORM="${OS}-${ARCH}"
    log_info "Detected platform: $PLATFORM"
}

# Download the agent binary
download_agent() {
    log_info "Downloading OffCall AI Agent..."

    if [ "$AGENT_VERSION" = "latest" ]; then
        DOWNLOAD_URL="https://github.com/${GITHUB_REPO}/releases/latest/download/${BINARY_NAME}-${PLATFORM}"
    else
        DOWNLOAD_URL="https://github.com/${GITHUB_REPO}/releases/download/${AGENT_VERSION}/${BINARY_NAME}-${PLATFORM}"
    fi

    # Try to download
    if command -v curl &> /dev/null; then
        curl -fsSL -o "/tmp/${BINARY_NAME}" "$DOWNLOAD_URL" || {
            log_warn "Download failed. Using local build fallback..."
            return 1
        }
    elif command -v wget &> /dev/null; then
        wget -q -O "/tmp/${BINARY_NAME}" "$DOWNLOAD_URL" || {
            log_warn "Download failed. Using local build fallback..."
            return 1
        }
    else
        log_error "Neither curl nor wget found. Please install one of them."
        exit 1
    fi

    return 0
}

# Install the agent
install_agent() {
    log_info "Installing agent..."

    # Create directories
    mkdir -p "$CONFIG_DIR" "$DATA_DIR"

    # Copy binary
    if [ -f "/tmp/${BINARY_NAME}" ]; then
        mv "/tmp/${BINARY_NAME}" "${INSTALL_DIR}/${BINARY_NAME}"
        chmod +x "${INSTALL_DIR}/${BINARY_NAME}"
    else
        log_error "Binary not found"
        exit 1
    fi

    log_info "Agent installed to ${INSTALL_DIR}/${BINARY_NAME}"
}

# Create configuration file
create_config() {
    log_info "Creating configuration..."

    if [ -z "$OFFCALL_API_KEY" ]; then
        log_warn "OFFCALL_API_KEY not set. You'll need to configure it manually."
        API_KEY="YOUR_API_KEY_HERE"
    else
        API_KEY="$OFFCALL_API_KEY"
    fi

    # Set API endpoint
    API_ENDPOINT="${OFFCALL_API_ENDPOINT:-http://localhost:8000/api/v1/metrics/ingest}"

    cat > "${CONFIG_DIR}/agent.yaml" << EOF
# OffCall AI Agent Configuration
# Generated by installer on $(date)

api:
  endpoint: ${API_ENDPOINT}
  api_key: ${API_KEY}
  timeout: 10s

collection:
  interval: 10s
  batch_size: 100

collectors:
  cpu: true
  memory: true
  disk: true
  network: true
  processes: true
  docker: true

tags:
  # Add your custom tags here
  # environment: production
  # service: my-service

buffer:
  enabled: true
  max_size: 10000
  flush_interval: 30s
  file_path: ${DATA_DIR}/buffer.json

logging:
  level: info
  format: json
EOF

    chmod 600 "${CONFIG_DIR}/agent.yaml"
    log_info "Configuration created at ${CONFIG_DIR}/agent.yaml"
}

# Create systemd service
create_systemd_service() {
    if [ ! -d "/etc/systemd/system" ]; then
        log_warn "systemd not found, skipping service creation"
        return
    fi

    log_info "Creating systemd service..."

    cat > /etc/systemd/system/offcall-agent.service << EOF
[Unit]
Description=OffCall AI Monitoring Agent
Documentation=https://github.com/cbrahmam/offcallai/blob/main/agent/README.md
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
ExecStart=${INSTALL_DIR}/${BINARY_NAME} --config ${CONFIG_DIR}/agent.yaml
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

# Security hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${DATA_DIR}
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    log_info "Systemd service created"
}

# Start the agent
start_agent() {
    if [ -d "/etc/systemd/system" ]; then
        log_info "Starting agent service..."
        systemctl enable offcall-agent
        systemctl start offcall-agent

        sleep 2
        if systemctl is-active --quiet offcall-agent; then
            log_info "Agent is running!"
        else
            log_error "Failed to start agent. Check logs with: journalctl -u offcall-agent -f"
        fi
    else
        log_info "To start the agent manually, run:"
        echo "  ${INSTALL_DIR}/${BINARY_NAME} --config ${CONFIG_DIR}/agent.yaml"
    fi
}

# Show completion message
show_completion() {
    echo ""
    echo "========================================"
    echo -e "${GREEN}OffCall AI Agent Installation Complete${NC}"
    echo "========================================"
    echo ""
    echo "Binary:  ${INSTALL_DIR}/${BINARY_NAME}"
    echo "Config:  ${CONFIG_DIR}/agent.yaml"
    echo "Data:    ${DATA_DIR}/"
    echo ""

    if [ -z "$OFFCALL_API_KEY" ]; then
        echo -e "${YELLOW}IMPORTANT: Edit ${CONFIG_DIR}/agent.yaml and add your API key${NC}"
        echo ""
    fi

    echo "Useful commands:"
    echo "  View logs:     journalctl -u offcall-agent -f"
    echo "  Restart:       systemctl restart offcall-agent"
    echo "  Stop:          systemctl stop offcall-agent"
    echo "  Status:        systemctl status offcall-agent"
    echo ""
    echo "Dashboard: http://localhost:3000/infrastructure"
    echo ""
}

# Uninstall function
uninstall() {
    log_info "Uninstalling OffCall AI Agent..."

    # Stop and disable service
    if [ -f "/etc/systemd/system/offcall-agent.service" ]; then
        systemctl stop offcall-agent 2>/dev/null || true
        systemctl disable offcall-agent 2>/dev/null || true
        rm -f /etc/systemd/system/offcall-agent.service
        systemctl daemon-reload
    fi

    # Remove files
    rm -f "${INSTALL_DIR}/${BINARY_NAME}"
    rm -rf "${CONFIG_DIR}"
    rm -rf "${DATA_DIR}"

    log_info "Uninstall complete"
}

# Main
main() {
    echo ""
    echo "========================================"
    echo "  OffCall AI Agent Installer"
    echo "========================================"
    echo ""

    # Check for uninstall flag
    if [ "$1" = "uninstall" ]; then
        check_root
        uninstall
        exit 0
    fi

    check_root
    detect_platform

    if download_agent; then
        install_agent
    else
        log_error "Failed to download agent. Please check your internet connection or install manually."
        exit 1
    fi

    create_config
    create_systemd_service
    start_agent
    show_completion
}

main "$@"
